=== Hsyy04/exp_wsd/trial/corpus/lexical-sample.dtd
<?xml version="1.0" encoding="ISO8859-1" ?>

<!ELEMENT corpus (lexelt+)>
<!ATTLIST corpus	  
	  lang CDATA #REQUIRED>

<!ELEMENT lexelt (instance+)>
<!ATTLIST lexelt	  
	  item CDATA #REQUIRED>          

<!ELEMENT instance (answer+, context+, postagging+)>
<!ATTLIST instance
          id  ID #REQUIRED>

<!ELEMENT answer EMPTY>
<!ATTLIST answer 
          instance  CDATA #IMPLIED
          senseid  CDATA #IMPLIED>

<!ELEMENT context (#PCDATA | head)*>

<!ELEMENT head (#PCDATA)>

<!ELEMENT postagging (word+)>

<!ELEMENT word (token+)>
<!ATTLIST word
          id CDATA #REQUIRED  
          pos  CDATA #IMPLIED>

<!ELEMENT token (#PCDATA)>

<!--  06-11-5
-->

=== Hsyy04/exp_wsd/trial/corpus/Chinese_test.xml
<?xml version="1.0" encoding="utf-8" ?>
<!DOCTYPE corpus SYSTEM "lexical-sample.dtd">

<corpus lang="Chinese">

<lexelt item="叫">

<instance id="叫.1">
<answer instance="叫.1" senseid=""/>
<context>

就是这卤牛肉，它能<head>叫</head>人白手起家成万元、十万元、百万元户。

</context>
<postagging>
<word id="0" pos="d">
<token>就</token>
</word>
<word id="1" pos="v">
<token>是</token>
</word>
<word id="2" pos="r">
<token>这</token>
</word>
<word id="3" pos="v">
<token>卤</token>
</word>
<word id="4" pos="n">
<token>牛肉</token>
</word>
<word id="5" pos="w">
<token>，</token>
</word>
<word id="6" pos="r">
<token>它</token>
</word>
<word id="7" pos="v">
<token>能</token>
</word>
<word id="8" pos="v">
<token>叫</token>
</word>
<word id="9" pos="n">
<token>人</token>
</word>
<word id="10" pos="i">
<token>白手起家</token>
</word>
<word id="11" pos="m">
<token>成万</token>
</word>
<word id="12" pos="q">
<token>元</token>
</word>
<word id="13" pos="w">
<token>、</token>
</word>
<word id="14" pos="m">
<token>十万</token>
</word>
<word id="15" pos="q">
<token>元</token>
</word>
<word id="16" pos="w">
<token>、</token>
</word>
<word id="17" pos="m">
<token>百万</token>
</word>
<word id="18" pos="q">
<token>元</token>
</word>
<word id="19" pos="Ng">
<token>户</token>
</word>
<word id="20" pos="w">
<token>。</token>
</word>
</postagging></instance>

<instance id="叫.2">
<answer instance="叫.2" senseid=""/>
<context>

上菜的太监那个馋相，祖父的师祖说不出来，只有一脸记忆，我也就记不下来，只觉祖父说这话时眉头一皱，眼睛一小，嘴几撇，一脸不屑与鄙薄，<head>叫</head>我至今忘不得。

</context>
<postagging>
<word id="0" pos="v">
<token>上</token>
</word>
<word id="1" pos="n">
<token>菜</token>
</word>
<word id="2" pos="u">
<token>的</token>
</word>
<word id="3" pos="n">
<token>太监</token>
</word>
<word id="4" pos="r">
<token>那个</token>
</word>
<word id="5" pos="n">
<token>馋相</token>
</word>
<word id="6" pos="w">
<token>，</token>
</word>
<word id="7" pos="n">
<token>祖父</token>
</word>
<word id="8" pos="u">
<token>的</token>
</word>
<word id="9" pos="n">
<token>师祖</token>
</word>
<word id="10" pos="v">
<token>说</token>
</word>
<word id="11" pos="d">
<token>不</token>
</word>
<word id="12" pos="v">
<token>出来</token>
</word>
<word id="13" pos="w">
<token>，</token>
</word>
<word id="14" pos="d">
<token>只</token>
</word>
<word id="15" pos="v">
<token>有</token>
</word>
<word id="16" pos="m">
<token>一</token>
</word>
<word id="17" pos="q">
<token>脸</token>
</word>
<word id="18" pos="vn">
<token>记忆</token>
</word>
<word id="19" pos="w">
<token>，</token>
</word>
<word id="20" pos="r">
<token>我</token>
</word>
<word id="21" pos="d">
<token>也</token>
</word>
<word id="22" pos="d">
<token>就</token>
</word>
<word id="23" pos="v">
<token>记</token>
</word>
<word id="24" pos="d">
<token>不</token>
</word>
<word id="25" pos="v">
<token>下来</token>
</word>
<word id="26" pos="w">
<token>，</token>
</word>
<word id="27" pos="d">
<token>只</token>
</word>
<word id="28" pos="v">
<token>觉</token>
</word>
<word id="29" pos="n">
<token>祖父</token>
</word>
<word id="30" pos="v">
<token>说</token>
</word>
<word id="31" pos="r">
<token>这</token>
</word>
<word id="32" pos="n">
<token>话</token>
</word>
<word id="33" pos="Ng">
<token>时</token>
</word>
<word id="34" pos="i">
<token>眉头一皱</token>
</word>
<word id="35" pos="w">
<token>，</token>
</word>
<word id="36" pos="n">
<token>眼睛</token>
</word>
<word id="37" pos="d">
<token>一</token>
</word>
<word id="38" pos="a">
<token>小</token>
</word>
<word id="39" pos="w">
<token>，</token>
</word>
<word id="40" pos="n">
<token>嘴</token>
</word>
<word id="41" pos="m">
<token>几</token>
</word>
<word id="42" pos="v">
<token>撇</token>
</word>
<word id="43" pos="w">
<token>，</token>
</word>
<word id="44" pos="m">
<token>一</token>
</word>
<word id="45" pos="q">
<token>脸</token>
</word>
<word id="46" pos="v">
<token>不屑</token>
</word>
<word id="47" pos="c">
<token>与</token>
</word>
<word id="48" pos="v">
<token>鄙薄</token>
</word>
<word id="49" pos="w">
<token>，</token>
</word>
<word id="50" pos="v">
<token>叫</token>
</word>
<word id="51" pos="r">
<token>我</token>
</word>
<word id="52" pos="d">
<token>至今</token>
</word>
<word id="53" pos="v">
<token>忘</token>
</word>
<word id="54" pos="d">
<token>不</token>
</word>
<word id="55" pos="u">
<token>得</token>
</word>
<word id="56" pos="w">
<token>。</token>
</word>
</postagging></instance>

<instance id="叫.3">
<answer instance="叫.3" senseid=""/>
<context>

”简直是当理不让，入木三分，读来<head>叫</head>人击节。

</context>
<postagging>
<word id="0" pos="w">
<token>”</token>
</word>
<word id="1" pos="d">
<token>简直</token>
</word>
<word id="2" pos="v">
<token>是</token>
</word>
<word id="3" pos="v">
<token>当</token>
</word>
<word id="4" pos="n">
<token>理</token>
</word>
<word id="5" pos="d">
<token>不</token>
</word>
<word id="6" pos="v">
<token>让</token>
</word>
<word id="7" pos="w">
<token>，</token>
</word>
<word id="8" pos="i">
<token>入木三分</token>
</word>
<word id="9" pos="w">
<token>，</token>
</word>
<word id="10" pos="v">
<token>读</token>
</word>
<word id="11" pos="v">
<token>来</token>
</word>
<word id="12" pos="v">
<token>叫</token>
</word>
<word id="13" pos="n">
<token>人</token>
</word>
<word id="14" pos="Vg">
<token>击</token>
</word>
<word id="15" pos="n">
<token>节</token>
</word>
<word id="16" pos="w">
<token>。</token>
</word>
</postagging></instance>

<instance id="叫.4">
<answer instance="叫.4" senseid=""/>
<context>

盘龙江一度污秽不堪、恶臭冲天，<head>叫</head>人心痛。

</context>
<postagging>
<word id="0" pos="ns">
<token>盘龙江</token>
</word>
<word id="1" pos="d">
<token>一度</token>
</word>
<word id="2" pos="n">
<token>污秽</token>
</word>
<word id="3" pos="v">
<token>不堪</token>
</word>
<word id="4" pos="w">
<token>、</token>
</word>
<word id="5" pos="n">
<token>恶臭</token>
</word>
<word id="6" pos="z">
<token>冲天</token>
</word>
<word id="7" pos="w">
<token>，</token>
</word>
<word id="8" pos="v">
<token>叫</token>
</word>
<word id="9" pos="n">
<token>人</token>
</word>
<word id="10" pos="a">
<token>心痛</token>
</word>
<word id="11" pos="w">
<token>。</token>
</word>
</postagging></instance>

<instance id="叫.5">
<answer instance="叫.5" senseid=""/>
<context>

世上竟有如此逼真的塑像，真<head>叫</head>我不能不叹服泰国的艺术家。

</context>
<postagging>
<word id="0" pos="s">
<token>世上</token>
</word>
<word id="1" pos="d">
<token>竟</token>
</word>
<word id="2" pos="v">
<token>有</token>
</word>
<word id="3" pos="r">
<token>如此</token>
</word>
<word id="4" pos="a">
<token>逼真</token>
</word>
<word id="5" pos="u">
<token>的</token>
</word>
<word id="6" pos="n">
<token>塑像</token>
</word>
<word id="7" pos="w">
<token>，</token>
</word>
<word id="8" pos="d">
<token>真</token>
</word>
<word id="9" pos="v">
<token>叫</token>
</word>
<word id="10" pos="r">
<token>我</token>
</word>
<word id="11" pos="d">
<token>不能不</token>
</word>
<word id="12" pos="vn">
<token>叹服</token>
</word>
<word id="13" pos="ns">
<token>泰国</token>
</word>
<word id="14" pos="u">
<token>的</token>
</word>
<word id="15" pos="n">
<token>艺术家</token>
</word>
<word id="16" pos="w">
<token>。</token>
</word>
</postagging></instance>

<instance id="叫.6">
<answer instance="叫.6" senseid=""/>
<context>

读到最快的新闻，得知今天的气温，拿到出门的地图，下载急需的软件，都能<head>叫</head>人长出一口气。

</context>
<postagging>
<word id="0" pos="v">
<token>读</token>
</word>
<word id="1" pos="v">
<token>到</token>
</word>
<word id="2" pos="d">
<token>最</token>
</word>
<word id="3" pos="a">
<token>快</token>
</word>
<word id="4" pos="u">
<token>的</token>
</word>
<word id="5" pos="n">
<token>新闻</token>
</word>
<word id="6" pos="w">
<token>，</token>
</word>
<word id="7" pos="v">
<token>得知</token>
</word>
<word id="8" pos="t">
<token>今天</token>
</word>
<word id="9" pos="u">
<token>的</token>
</word>
<word id="10" pos="n">
<token>气温</token>
</word>
<word id="11" pos="w">
<token>，</token>
</word>
<word id="12" pos="v">
<token>拿</token>
</word>
<word id="13" pos="v">
<token>到</token>
</word>
<word id="14" pos="v">
<token>出门</token>
</word>
<word id="15" pos="u">
<token>的</token>
</word>
<word id="16" pos="n">
<token>地图</token>
</word>
<word id="17" pos="w">
<token>，</token>
</word>
<word id="18" pos="v">
<token>下载</token>
</word>
<word id="19" pos="v">
<token>急需</token>
</word>
<word id="20" pos="u">
<token>的</token>
</word>
<word id="21" pos="n">
<token>软件</token>
</word>
<word id="22" pos="w">
<token>，</token>
</word>
<word id="23" pos="d">
<token>都</token>
</word>
<word id="24" pos="v">
<token>能</token>
</word>
<word id="25" pos="v">
<token>叫</token>
</word>
<word id="26" pos="n">
<token>人</token>
</word>
<word id="27" pos="a">
<token>长</token>
</word>
<word id="28" pos="v">
<token>出</token>
</word>
<word id="29" pos="m">
<token>一</token>
</word>
<word id="30" pos="q">
<token>口</token>
</word>
<word id="31" pos="n">
<token>气</token>
</word>
<word id="32" pos="w">
<token>。</token>
</word>
</postagging></instance>

<instance id="叫.7">
<answer instance="叫.7" senseid=""/>
<context>

三年来被温书军无故殴打的就有26人之多，就这样一伙恶贯满盈的犯罪分子，检察机关竟以事实不清，证据不足，不予批捕，使温更加嚣张，并扬言谁要到公安局再告他就<head>叫</head>他白刀子进红刀子出。

</context>
<postagging>
<word id="0" pos="m">
<token>三</token>
</word>
<word id="1" pos="q">
<token>年</token>
</word>
<word id="2" pos="f">
<token>来</token>
</word>
<word id="3" pos="p">
<token>被</token>
</word>
<word id="4" pos="nr">
<token>温</token>
</word>
<word id="5" pos="nr">
<token>书军</token>
</word>
<word id="6" pos="d">
<token>无故</token>
</word>
<word id="7" pos="v">
<token>殴打</token>
</word>
<word id="8" pos="u">
<token>的</token>
</word>
<word id="9" pos="d">
<token>就</token>
</word>
<word id="10" pos="v">
<token>有</token>
</word>
<word id="11" pos="m">
<token>26</token>
</word>
<word id="12" pos="n">
<token>人</token>
</word>
<word id="13" pos="u">
<token>之</token>
</word>
<word id="14" pos="a">
<token>多</token>
</word>
<word id="15" pos="w">
<token>，</token>
</word>
<word id="16" pos="d">
<token>就</token>
</word>
<word id="17" pos="r">
<token>这样</token>
</word>
<word id="18" pos="m">
<token>一</token>
</word>
<word id="19" pos="q">
<token>伙</token>
</word>
<word id="20" pos="i">
<token>恶贯满盈</token>
</word>
<word id="21" pos="u">
<token>的</token>
</word>
<word id="22" pos="vn">
<token>犯罪</token>
</word>
<word id="23" pos="n">
